env:
  browser: true
  node: true
  es6: true
extends: "eslint:recommended"
parserOptions:
  ecmaVersion: 2015
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
