plugins:
  - jest
env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - "eslint:recommended"
  - "plugin:jest/recommended"
parserOptions:
  ecmaVersion: 9
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
